<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CASEAdmin\Module'                        => __DIR__ . '/Module.php',
    'CASEAdmin\Controller\AdminController' => __DIR__ . '/src/CASEAdmin/Controller/AdminController.php',
    'CASEAdminTest\Framework\TestCase'        => __DIR__ . '/tests/CASEAdmin/Framework/TestCase.php',
    'CASEAdminTest\SampleTest'                => __DIR__ . '/tests/CASEAdmin/SampleTest.php',
);
