<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CaseLog\Module'                        => __DIR__ . '/Module.php',
    'CaseLog\Controller\LogController' => __DIR__ . '/src/CaseLog/Controller/LogController.php',
    'CaseLogTest\Framework\TestCase'        => __DIR__ . '/tests/CaseLog/Framework/TestCase.php',
    'CaseLogTest\SampleTest'                => __DIR__ . '/tests/CaseLog/SampleTest.php',
);
