<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CASELog\Module'                        => __DIR__ . '/Module.php',
    'CASELog\Controller\LogController' => __DIR__ . '/src/CASELog/Controller/LogController.php',
    'CASELogTest\Framework\TestCase'        => __DIR__ . '/tests/CASELog/Framework/TestCase.php',
    'CASELogTest\SampleTest'                => __DIR__ . '/tests/CASELog/SampleTest.php',
);
