<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CASENavigation\Module'                        => __DIR__ . '/Module.php',
    'CASENavigation\Controller\NavigationController' => __DIR__ . '/src/CASENavigation/Controller/NavigationController.php',
    'CASENavigationTest\Framework\TestCase'        => __DIR__ . '/tests/CASENavigation/Framework/TestCase.php',
    'CASENavigationTest\SampleTest'                => __DIR__ . '/tests/CASENavigation/SampleTest.php',
);
