<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CASEBaseDiagnostics\Module'                        => __DIR__ . '/Module.php',
    'CASEBaseDiagnostics\Controller\DiagnosticsController' => __DIR__ . '/src/CASEBaseDiagnostics/Controller/DiagnosticsController.php',
    'CASEBaseDiagnosticsTest\Framework\TestCase'        => __DIR__ . '/tests/CASEBaseDiagnostics/Framework/TestCase.php',
    'CASEBaseDiagnosticsTest\SampleTest'                => __DIR__ . '/tests/CASEBaseDiagnostics/SampleTest.php',
);
