<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CASEBase\Module'                        => __DIR__ . '/Module.php',
    'CASEBase\Controller\CaseController' => __DIR__ . '/src/CASEBase/Controller/CaseController.php',
    'CASEBaseTest\Framework\TestCase'        => __DIR__ . '/tests/CASEBase/Framework/TestCase.php',
    'CASEBaseTest\SampleTest'                => __DIR__ . '/tests/CASEBase/SampleTest.php',
);
