<ul class="nav nav-list well well-small">
    <li><a href="<?= $this->url('admin', array('action' => 'list-users')); ?>"><i class="icon-chevron-right"></i> List Users</a></li>
    <li><a href="<?= $this->url('admin', array('action' => 'update-schema')); ?>"><i class="icon-chevron-right"></i> Update Schema</a></li>
    <li><a href="<?= $this->url('admin', array('action' => 'create-schema')); ?>"><i class="icon-chevron-right"></i> View Schema SQL</a></li>
    <li><a href="<?= $this->url('course'); ?>"><i class="icon-chevron-right"></i> Manage Courses</a></li>
</ul>

