<?php
/** @var $field \Zend\Form\Element */
$messages = $field->getMessages();
$label    = $field->getLabel();
$class    = $field->getAttribute('class');
$prepend  = $field->getAttribute('data-prepend');
$append   = $field->getAttribute('data-append');
$apclass  = array();

if ($prepend) {
    $apclass[] = 'input-prepend';
    $field->setAttribute('data-prepend', null);
}
if ($append)  {
    $apclass[] = 'input-append';
    $field->setAttribute('data-append', null);
}
?>
<div class="control-group<?php if (!empty($messages)): ?> error<?php endif; ?>">
    <?php if ($label): ?>
    <label class="control-label" for="<?= $field->getName(); ?>"><?= $label; ?></label>
    <?php endif; ?>
    <div class="controls">
        <?php if (!empty($apclass)): ?><div class="<?= implode(' ', $apclass); ?>"><?php endif; ?>
        <?php if ($prepend): ?><?= $prepend; ?><?php endif; ?>
        <?= $this->formElement($field); ?>
        <?php if ($append): ?><?= $append; ?><?php endif; ?>
        <?php if ($messages): ?>
        <span class="help-inline"><?= array_shift($messages); ?></span>
        <?php endif; ?>
        <?php if (!empty($apclass)): ?></div><?php endif; ?>
    </div>
</div>
