<div class="row">
    <div class="span3">
        <?= $this->partial('application/admin/partial/navigation'); ?>
    </div>
    <div class="span9">
        <div class="well">
            <h2>System users</h2>
        </div>
        <table class="table table-bordered table-striped">
            <?php foreach ($people as $person): ?>
            <tr>
                <td><?= $person->getName(); ?></td>
                <td><?= $person->getRoleId(); ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
