<div class="well">
    <h1>Register for Classes</h1>
    <?php if (isset($mysecret)): ?>
        <h2 style="color:red;"><?= $mysecret; ?></h2>
    <?php endif; ?>
</div>

<table class="table table-bordered table-striped table-condensed">
    
    <tr>
        <th>Select Course Name</th>
        <th>Select Course Number</th>
        <th class="span2"><a href="#">Add Course</a></th>
    </tr>
    
</table>