<h2>SQL Schema Generator</h2>

<?php if (isset($success)): ?>
<div class="alert alert-block alert-success">
    <h2>Success!</h2>
    The database has been updated.
</div>
<?php endif; ?>

<table class="table table-striped table-bordered">
    <?php if (isset($sql)): ?>
    <?php foreach ($sql as $statement): ?>
        <tr>
            <td><?= $statement; ?></td>
        </tr>
    <?php endforeach; ?>
    <?php endif; ?>
</table>

<form action="" method="POST" name="unit" class="form" id="unit">
    <div class="form-actions">
        <input type="submit" name="cancel" class="btn pull-left" value="Cancel">
        <input type="submit" name="submit" class="btn btn-warning pull-right" value="Run Queries">
    </div>
</form>
