<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('CASE Skelleton App'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sCASE Skeleton Application%s. You are currently running Zend Framework version %s.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
</div>

