<div class="hero-unit">
    <h1>Southern Iowa Community College</h1>
    <p>Welcome to the SICC Web page.</p>
    </div>

<div class="row">
    <div class="span4">
        <h1>News</h1>
        <p>news</p>
    </div>

    <div class="span4">
        <h1>About SICC</h1>
        <p>about</p>
   </div>

   <div class="span4">
       <h1>Events</h1>
       <p><a href="irc://irc.freenode.net/zftalk.2">Irc</a></p>
   </div>
</div>
