<?php


?>


 <body>
     
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SICC</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <a href="#" class="navbar-link">Username</a>
            </p>
            <ul class="nav">
             
              <li><a href="<?php echo $this->url('home') . ($this->redirect ? '?redirect='.$this->redirect : '')?>">Home</a></li>
              <li><a href="#about">Log out</a></li>
              <li class="active"><a href="#contact">Profile</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Actions</li>
              <li class="active"><a href="#">Edit Profile</a></li>
              <li><a href="#">Register for classes</a></li>
              <li><a href="#">View Schedule</a></li>
              <li><a href="#">Graduation Progress</a></li>
              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1>Hello,User!</h1>
            <p>Welcome to your university profile page.</p>
          </div>
            <form>
                <fieldset>
                    <legend>Change Email</legend>
                    <label>Enter old email</label>
                        <input type="text"placeholder="Type here..">
                        <label>Enter new email</label>
                        <input type="text"placeholder="Type here..">
                        <label class="">
                            
                        </label>
                        <button type="submit"class="btn">Submit Changes</button>
                </fieldset>
            </form>
            <form>
                <fieldset>
                    <legend>Change Password</legend>
                    <label>Enter old password</label>
                        <input type="text"placeholder="Type here..">
                        <label>Enter new password</label>
                        <input type="text"placeholder="Type here..">
                        <label class="">
                            
                        </label>
                        <button type="submit"class="btn">Submit Changes</button>
                </fieldset>
            </form>
          <div class="row-fluid">
            <div class="span4">
              
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; 2012 by Heefe Technologies, inc. All rights reserved.</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
