<?php
/** @var $identity \Application\Entity\Person */
$identity = $this->zfcUserIdentity();

// Technically, this would be better placed in the controller.
$nsArr    = explode('\\', get_class($identity));
$userType = array_pop($nsArr);
?>

<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($identity->getEmail()) ?></div>
<h3>Hello, <?php echo $identity->getDisplayName(); ?>!</h3>

<p><?= $userType; ?></p>


<div style="float:left">
<div class="hero-unit">
<ul class="nav nav-list">
    <ul class="nav-header">Actions</ul>
    <ul class="active"><a href="#">View Profile</a></ul> 
    <ul><a href="#">Register for Classes</a></ul>
    <ul><a href="#">View Schedule</a></ul>
    <ul><a href="<?php echo $this->url('zfcuser/logout') ?>">[Log Out]</a></ul>
</ul>
</div>
</div>

<div style="clear:both;"></div>
